name: polar_analysis_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - jupyterlab
  - scikit-learn
  - statsmodels
  - plotly
  - matplotlib
  - scipy
  - python-kaleido
  - pip
  - pip:
      - polar_diagrams
